# to jsem rad ze to funguje
# Tento playbook vypíše hostname a porovná čas s online zdrojem (worldclockapi.com)
# oje
- name: Print hostname and compare time with online source
  hosts: all
  gather_facts: true
  vars:
    time_tolerance_seconds: 10

  tasks:
    - name: Show hostname
      ansible.builtin.debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Get online time (worldclockapi.com)
      ansible.builtin.uri:
        url: http://worldclockapi.com/api/json/utc/now
        method: GET
        return_content: true
      register: worldtime
      retries: 3
      delay: 2
      until: worldtime.status == 200
      failed_when:
        - worldtime.status != 200
        - worldtime.json is not defined
        - worldtime.json.currentFileTime is not defined

    - name: Compute time difference
      ansible.builtin.set_fact:
        time_diff_abs: "{{ (ansible_date_time.epoch | int) - (((worldtime.json.currentFileTime | int) // 10000000) - 11644473600) | abs }}"

    - name: Show time comparison
      ansible.builtin.debug:
        msg: "Time difference (seconds): {{ time_diff_abs }} | Tolerance: {{ time_tolerance_seconds }}"

    - name: Fail if time difference exceeds tolerance
      ansible.builtin.fail:
        msg: "Time difference ({{ time_diff_abs }}s) exceeds tolerance of {{ time_tolerance_seconds }}s"
      when: time_diff_abs | int > time_tolerance_seconds | int
