- name: Print hostname and compare time with online source
  hosts: all
  gather_facts: false
  vars:
    time_tolerance_seconds: 10

  tasks:
    - name: Get hostname
      ansible.builtin.command: hostname
      register: hostname_out
      changed_when: false

    - name: Show hostname
      ansible.builtin.debug:
        msg: "Hostname: {{ hostname_out.stdout }}"

    - name: Get server time (epoch seconds, UTC)
      ansible.builtin.command: date -u +%s
      register: server_time
      changed_when: false

    - name: Get online time (worldclockapi.com)
      ansible.builtin.uri:
        url: http://worldclockapi.com/api/json/utc/now
        method: GET
        return_content: true
      register: worldtime
      retries: 3
      delay: 2
      until: worldtime.status == 200
      failed_when:
        - worldtime.status != 200
        - worldtime.json is not defined
        - worldtime.json.currentFileTime is not defined

    - name: Compute epochs and time difference
      ansible.builtin.set_fact:
        server_epoch: "{{ server_time.stdout | int }}"
        online_epoch: "{{ ((worldtime.json.currentFileTime | int) // 10000000) - 11644473600 }}"
        time_diff: "{{ (server_time.stdout | int) - (((worldtime.json.currentFileTime | int) // 10000000) - 11644473600) }}"
        time_diff_abs: "{{ ((server_time.stdout | int) - (((worldtime.json.currentFileTime | int) // 10000000) - 11644473600)) | abs | int }}"

    - name: Show time comparison
      ansible.builtin.debug:
        msg:
          - "Server epoch: {{ server_epoch }}"
          - "Online epoch: {{ online_epoch }}"
          - "Difference (seconds): {{ time_diff }} (abs: {{ time_diff_abs }})"
          - "Tolerance (seconds): {{ time_tolerance_seconds }}"

    - name: Fail if time difference exceeds tolerance
      ansible.builtin.fail:
        msg: "Time difference ({{ time_diff_abs }}s) exceeds tolerance of {{ time_tolerance_seconds }}s"
      when: time_diff_abs | int > time_tolerance_seconds | int
