# Tento playbook nahraje a spustí inline skript na vzdáleném hostu a vypíše jeho výstup
- name: Upload and execute inline script and print its output
  hosts: all
  gather_facts: false
  vars:
    script_name: uploaded_script.sh
    script_path: "/tmp/{{ script_name }}"
    script_content: |
      #!/usr/bin/env bash
      set -euo pipefail
      echo "Script běží na: $(hostname)"
      ls -1 /tmp > /tmp/tmp_dir_list.txt
      echo "Directory listing saved to /tmp/tmp_dir_list.txt on $(hostname)"
      echo "Čas: $(date -Iseconds)"
      echo "Uživatel: $(whoami)"
  tasks:
    - name: Ensure tmp_dir_lists directory exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}/tmp_dir_lists"
        state: directory
    - name: Ensure tmp_dir_lists directory exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}/tmp_dir_lists"
        state: directory

    - name: Upload, execute and print output; always clean up
      block:
        - name: Upload inline script to remote host
          ansible.builtin.copy:
            dest: "{{ script_path }}"
            content: "{{ script_content }}"
            mode: '0755'

        - name: Execute the script
          ansible.builtin.shell: "{{ script_path }}"
          args:
            executable: /bin/bash
          register: script_result

        - name: Print script STDOUT (multiline)
          ansible.builtin.debug:
            var: script_result.stdout_lines

        - name: Fetch /tmp directory listing from server
          ansible.builtin.fetch:
            src: /tmp/tmp_dir_list.txt
            dest: "{{ playbook_dir }}/tmp_dir_lists/{{ inventory_hostname }}_tmp_dir_list.txt"
            flat: yes

        - name: Compare /tmp directory listings
          ansible.builtin.shell: "diff {{ playbook_dir }}/tmp_dir_lists/{{ groups['testservers'][0] }}_tmp_dir_list.txt {{ playbook_dir }}/tmp_dir_lists/{{ groups['testservers'][1] }}_tmp_dir_list.txt"
          register: diff_result
          delegate_to: localhost
          failed_when: diff_result.rc == 2

        - name: Print /tmp directory differences
          ansible.builtin.debug:
            var: diff_result.stdout_lines
          delegate_to: localhost

        - name: Print script STDERR (if any, multiline)
          ansible.builtin.debug:
            var: script_result.stderr_lines
          when: (script_result.stderr_lines | default([])) | length > 0
      always:
        - name: Remove uploaded script
          ansible.builtin.file:
            path: "{{ script_path }}"
            state: absent

        - name: Remove /tmp directory listing from remote server
          ansible.builtin.file:
            path: /tmp/tmp_dir_list.txt
            state: absent
