# Tento playbook nahraje a spustí inline skript na vzdáleném hostu a vypíše jeho výstup
- name: Upload and execute inline script and print its output
  hosts: all
  gather_facts: false
  vars:
    script_name: uploaded_script.sh
    script_path: "/tmp/{{ script_name }}"
    script_content: |
      #!/usr/bin/env bash
      set -euo pipefail
      echo "Script běží na: $(hostname)"
      ls -1 /tmp > /tmp/tmp_dir_list.txt
      echo "Directory listing saved to /tmp/tmp_dir_list.txt on $(hostname)"
      echo "Čas: $(date -Iseconds)"
      echo "Uživatel: $(whoami)"
  tasks:
    - name: Upload, execute and print output; always clean up
      block:
        - name: Upload inline script to remote host
          ansible.builtin.copy:
            dest: "{{ script_path }}"
            content: "{{ script_content }}"
            mode: '0755'

        - name: Execute the script
          ansible.builtin.shell: "{{ script_path }}"
          args:
            executable: /bin/bash
          register: script_result

        - name: Print script STDOUT (multiline)
          ansible.builtin.debug:
            var: script_result.stdout_lines

        - name: Fetch /tmp directory listing from server
          ansible.builtin.fetch:
            src: /tmp/tmp_dir_list.txt
            dest: "{{ playbook_dir }}/tmp_dir_lists/{{ inventory_hostname }}_tmp_dir_list.txt"
            flat: yes

        - name: Print script STDERR (if any, multiline)
          ansible.builtin.debug:
            var: script_result.stderr_lines
          when: (script_result.stderr_lines | default([])) | length > 0
      always:
        - name: Remove uploaded script
          ansible.builtin.file:
            path: "{{ script_path }}"
            state: absent
