- name: Upload and execute inline script and print its output
  hosts: all
  gather_facts: false
  vars:
    script_name: uploaded_script.sh
    script_path: "/tmp/{{ script_name }}"
    script_content: |
      #!/usr/bin/env bash
      set -euo pipefail
      echo "Script běží na: $(hostname)"
      echo "Čas: $(date -Iseconds)"
      echo "Uživatel: $(whoami)"
  tasks:
    - name: Upload inline script to remote host
      ansible.builtin.copy:
        dest: "{{ script_path }}"
        content: "{{ script_content }}"
        mode: '0755'

    - name: Execute the script
      ansible.builtin.shell: "{{ script_path }}"
      args:
        executable: /bin/bash
      register: script_result

    - name: Print script STDOUT
      ansible.builtin.debug:
        msg: |
          --- STDOUT ---
          {{ script_result.stdout | default('') }}

    - name: Print script STDERR (if any)
      ansible.builtin.debug:
        msg: |
          --- STDERR ---
          {{ script_result.stderr }}
      when: (script_result.stderr | default('')) | length > 0

    - name: Remove uploaded script
      ansible.builtin.file:
        path: "{{ script_path }}"
        state: absent
